# Generated by Django 4.2.6 on 2023-10-19 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_project_fri_project_mon_project_sat_project_sun_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='coins',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
