# Generated by Django 4.2.6 on 2024-01-26 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='limit_activity_per_day',
            field=models.PositiveIntegerField(default=1, null=True),
        ),
    ]
