# Generated by Django 4.2.6 on 2024-01-26 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_project_limit_activity_per_day'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='limit_activity_per_day',
            new_name='max_activity_per_day',
        ),
    ]
