# Generated by Django 4.2.6 on 2024-01-26 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_rename_limit_activity_per_day_project_max_activity_per_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='activity_code',
            field=models.ImageField(blank=True, null=True, upload_to='activity_codes/'),
        ),
    ]
