# Generated by Django 4.2.6 on 2024-01-26 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_project_activity_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='credited_coins',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
