# Generated by Django 4.2.3 on 2023-08-15 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0002_centeradmin_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='uid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
