# Generated by Django 4.2.3 on 2023-08-16 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0003_customuser_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
