# Generated by Django 4.2.3 on 2023-08-16 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0005_alter_customuser_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='redeemed_coins',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
