# Generated by Django 4.2.6 on 2024-01-26 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0006_userprofile_redeemed_coins'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='redeemed_coins',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='coins',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
